// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/config/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Configs service

type ConfigsService interface {
	// 根据 唯一 获取配置设置
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 更新配置设置
	Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type configsService struct {
	c    client.Client
	name string
}

func NewConfigsService(name string, c client.Client) ConfigsService {
	return &configsService{
		c:    c,
		name: name,
	}
}

func (c *configsService) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Configs.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configsService) Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Configs.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Configs service

type ConfigsHandler interface {
	// 根据 唯一 获取配置设置
	Get(context.Context, *Request, *Response) error
	// 更新配置设置
	Update(context.Context, *Request, *Response) error
}

func RegisterConfigsHandler(s server.Server, hdlr ConfigsHandler, opts ...server.HandlerOption) error {
	type configs interface {
		Get(ctx context.Context, in *Request, out *Response) error
		Update(ctx context.Context, in *Request, out *Response) error
	}
	type Configs struct {
		configs
	}
	h := &configsHandler{hdlr}
	return s.Handle(s.NewHandler(&Configs{h}, opts...))
}

type configsHandler struct {
	ConfigsHandler
}

func (h *configsHandler) Get(ctx context.Context, in *Request, out *Response) error {
	return h.ConfigsHandler.Get(ctx, in, out)
}

func (h *configsHandler) Update(ctx context.Context, in *Request, out *Response) error {
	return h.ConfigsHandler.Update(ctx, in, out)
}
